#resolver: lts-9.0
#resolver: lts-10.3
# resolver: lts-13.6
resolver: lts-14.4
extra-deps:
  - ../beam/beam-core

# Problem: MacOS build failure
# >   Configuring mysql-0.1.7...
# >   setup: Missing dependencies on foreign libraries:
# >   * Missing (or bad) C libraries: ssl, crypto
# Possible solution:
# https://github.com/depressed-pho/HsOpenSSL/issues/41
# TODO: how to make it portable?
extra-include-dirs:
- /usr/local/opt/openssl/include
extra-lib-dirs:
- /usr/local/opt/openssl/lib
